const FIELD_TYPES = require('../FieldsTypes');
const COMMON_FIELDS = require('../CommonFields');

const EXTERNAL_EQUIPMENT_COMMON_FIELDS = [
  ...COMMON_FIELDS.BASIC_INFO,
  ...COMMON_FIELDS.RACK_INFO,
  ...COMMON_FIELDS.OWNER_ENTITY,
  ...COMMON_FIELDS.COMPLETE_LOCATION,
  ...COMMON_FIELDS.PORT_LIST,
  ...COMMON_FIELDS.COMMENTS_FIELDS,
  ...COMMON_FIELDS.USER_CREATOR_MODIFIER_FIELDS,
];

const EXTERNAL_EQUIPMENT_SUNET = [];

const EXTERNAL_EQUIPMENT_NORDUNI = [];

module.exports = {
  EXTERNAL_EQUIPMENT_COMMON_FIELDS,
  EXTERNAL_EQUIPMENT_SUNET,
  EXTERNAL_EQUIPMENT_NORDUNI,
};
