const FIELD_TYPES = require('../FieldsTypes');
const COMMON_FIELDS = require('../CommonFields');

const OPTICALPATH_COMMON_FIELDS = [
  ...COMMON_FIELDS.BASIC_INFO,
  ...COMMON_FIELDS.COMMENTS_FIELDS,
  ...COMMON_FIELDS.USER_CREATOR_MODIFIER_FIELDS,
];

const OPTICALPATH_SUNET = [];

const OPTICALPATH_NORDUNI = [];

module.exports = {
  OPTICALPATH_COMMON_FIELDS,
  OPTICALPATH_SUNET,
  OPTICALPATH_NORDUNI,
};
