const SHOW_NEW_CONTACT_FORM = "SHOW_NEW_CONTACT_FORM";
const HIDE_NEW_CONTACT_FORM = "HIDE_NEW_CONTACT_FORM";
// const SAVE_NEW_CONTACT = 'SAVE_NEW_CONTACT';

// const EDIT_CONTACT = 'EDIT_CONTACT';

export default {
    SHOW_NEW_CONTACT_FORM,
    HIDE_NEW_CONTACT_FORM,
};
