const SHOW_NEW_CONTACT_FORM = 'SHOW_NEW_CONTACT_FORM';
const HIDE_NEW_CONTACT_FORM = 'HIDE_NEW_CONTACT_FORM';
const SHOW_CONTACT_DETAIL_FORM = 'SHOW_CONTACT_DETAIL_FORM';
const DELETE_CONTACT = 'DELETE_CONTACT';
// const SAVE_NEW_CONTACT = 'SAVE_NEW_CONTACT';

// const EDIT_CONTACT = 'EDIT_CONTACT';

export default {
  SHOW_NEW_CONTACT_FORM,
  HIDE_NEW_CONTACT_FORM,
  SHOW_CONTACT_DETAIL_FORM,
  DELETE_CONTACT,
};
