const SHOW_MODAL_CONFIRM = 'SHOW_MODAL_CONFIRM';
const HIDE_MODAL_CONFIRM = 'HIDE_MODAL_CONFIRM';
const CONFIRM_CREATED_IN_MODAL = 'CONFIRM_CREATED_IN_MODAL';
const CONFIRM_EDITED_IN_MODAL = 'CONFIRM_EDITED_IN_MODAL';
const CONFIRM_DELETED_IN_MODAL = 'CONFIRM_DELETED_IN_MODAL';

export default {
  SHOW_MODAL_CONFIRM,
  HIDE_MODAL_CONFIRM,
  CONFIRM_CREATED_IN_MODAL,
  CONFIRM_EDITED_IN_MODAL,
  CONFIRM_DELETED_IN_MODAL,
};
