const SHOW_MODAL_FORM = 'SHOW_MODAL_FORM';
const HIDE_MODAL_FORM = 'HIDE_MODAL_FORM';
const SHOW_MODAL_DETAIL_FORM = 'SHOW_MODAL_DETAIL_FORM';
const SHOW_MODAL_EDIT_FORM = 'SHOW_MODAL_EDIT_FORM';
const ROW_CREATED_IN_MODAL = 'ROW_CREATED_IN_MODAL';
const ROW_EDITED_IN_MODAL = 'ROW_EDITED_IN_MODAL';
const ROW_DELETED_IN_MODAL = 'ROW_DELETED_IN_MODAL';

export default {
  SHOW_MODAL_FORM,
  HIDE_MODAL_FORM,
  SHOW_MODAL_DETAIL_FORM,
  SHOW_MODAL_EDIT_FORM,
  ROW_CREATED_IN_MODAL,
  ROW_EDITED_IN_MODAL,
  ROW_DELETED_IN_MODAL,
};
