const SEARCH_START = 'SEARCH_START';
const SEARCH_SUCCESS = 'SEARCH_START';
const SEARCH_ERROR = 'SEARCH_ERROR';
const SEARCH_CLEAN = 'SEARCH_CLEAN';

export default {
  SEARCH_START,
  SEARCH_SUCCESS,
  SEARCH_ERROR,
  SEARCH_CLEAN,
};
