const Routes = {
    "/": "Home",
    "/dashboard": "Dashboard",
    "/network": "Network",
    "/network/physical": "Physical",
    "/network/physical/cables": "Cables",
    "/network/physical/external-equipment": "External equipment",
    "/network/physical/firewalls": "Firewalls",
    "/network/physical/hosts": "Hosts",
    "/network/physical/odfs": "Odfs",
    "/network/physical/optical-nodes": "Optical nodes",
    "/network/physical/routers": "Routers",
    "/network/logical": "Logical",
    "/network/logical/hosts": "Hosts",
    "/network/logical/optical-links": "Optical links",
    "/network/logical/optical-multiplex": "Optical multiplex",
    "/network/logical/optical-paths": "Optical paths",
    "/network/locations": "Locations",
    "/network/locations/racks": "Racks",
    "/network/locations/sites": "Sites",
    "/services": "Services",
    "/community": "Community",
    "/community/organizations": "Organizations",
    "/community/organizations/provider": "Provider",
    "/community/organizations/customers": "Customers",
    "/community/organizations/end-users": "End users",
    "/community/groups": "Groups",
    "/community/contacts": "Contacts",
    "/community/roles": "Roles",
    "/community/contacts/create": "Create Contact",
    "/community/contacts/:contactId": "Contact Info",
    "/personal-area": "Personal Area",
    "/personal-area/profile": "Profile",
    "/personal-area/settings": "Settings"
};

export default Routes;
