# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:

  unittests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install requirements
        run: npm install

      - name: Setup tests
        run: |
          npm run adapt-queries common
          npm run relay-common

      - name: Run tests
        run: npm run test

      - name: Check code with prettier (no-fail)
        run: npm run check-code || true

      - name: Check styles with prettier (no-fail)
        run: npm run check-styles || true

      - name: Test build
        run: npm run-script build

      - name: Audit (no-fail)
        # Don't error out on this until we are somewhere close to up-to-date.
        run: npm audit || true
